require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  # 接続先は config/redis.yml が環境・用途ごとに決める (development のキャッシュは db 0)。
  config.cache_store = :redis_cache_store, {
    url: Rails.application.config_for(:redis)[:cache_url],
    # キャッシュは「速いか、無いか」のどちらかであるべきなので、既定 (1 秒) より短く切る。
    # 待たされるくらいならミス扱いにして計算し直した方が総合的に速い。
    connect_timeout: 1,
    read_timeout: 0.2,
    write_timeout: 0.2,
    reconnect_attempts: 1,
    pool: { size: ENV.fetch("RAILS_MAX_THREADS", 5).to_i },
    # 既定のハンドラでも接続断は握りつぶされる (read は nil、fetch はブロックに
    # フォールバック) が、ログに埋もれるのでエラートラッカーへ送る。
    error_handler: ->(method:, returning:, exception:) {
      Rails.error.report(exception, handled: true, context: { method: method, returning: returning })
    }
  }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # ジョブは production と同じ Sidekiq で動かす。キューは Redis の db 2
  # (config/redis.yml の queue_url)、処理は worker コンテナ。
  config.active_job.queue_adapter = :sidekiq

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
